### ISSUE TITLE
Plan of code release

### ISSUE THREAD

**Issue by fzy139** [eckertzhang/Text2NeRF#1]
Hi,

Thanks for your excellent work. When will the code be released?

**Comment by abhigoku10** [comment]
@fzy139  when is the code going to be release ??
Thanks in advance

**Comment by Dragonkingpan** [comment]
同问 from china

**Comment by blacksino** [comment]
一个月了还是没代码

**Comment by blacksino** [comment]
别等了 这哥们一作的文章基本都是建了个空的repo，然后就是release soon，说的好听叫没诚意，不好听就有学术造假嫌疑

**Comment by eckertzhang** [comment]
This work is still under review. We will release the code when the paper is accepted.

**Comment by eckertzhang** [comment]
Thank you for your attention. The code has been released.
