### ISSUE TITLE
Extracting the mesh

### ISSUE THREAD

**Issue by NikitaVasilevN** [eckertzhang/Text2NeRF#4]
Dear author, thank you for publishing the code.
Could you please provide additional code to extract the mesh. I see you have the convert_sdf_samples_to_ply function, but you don't call it. Thank you in advance

**Comment by Asianfleet** [comment]
hi,have you solved it?

**Comment by NikitaVasilevN** [comment]
yes, I did.
I have used code from TensoRF https://github.com/apchenstu/TensoRF/blob/main/train.py and copy export_mesh function
